### ISSUE TITLE
Mols-Linjen crashes the game

### ISSUE THREAD

**Issue by algorythm** [hold11/CDIO_final#90]
```
----------------------------------------
-- Current Player: Ove --
----------------------------------------
Starting balance: 27200.
Player in jail: false.

Player rolled [6] and [4].
Player landed on "De fÃ¦ngsles".
   Field Type: Jail.
   [Rest Passed]: 
      Ove has received 4000 for passing START.
Player rolled [5] and [2].

End balance: 31200


----------------------------------------
-- Current Player: Dirch --
----------------------------------------
Starting balance: 20000.
Player in jail: false.

Player rolled [5] and [6].
Player landed on "Frederiksberggade".
LandPlot.
   Rent: 1400
Current field is for sale.
[Ownable]: Dirch just bought Frederiksberggade
   Player chose to buy the field for 7000.

End balance: 13000


----------------------------------------
-- Current Player: Inger --
----------------------------------------
Starting balance: 21800.
Player in jail: false.

Player rolled [4] and [3].
Player landed on "PrÃ¸v lykken".
   Field Type: ChanceField.
Tag med Mols-Linen. Flyt brikken frem, og hvis De passerer âSTARTâ, indkassÃ©r da kr. 4.000.
Exception in thread "main" java.lang.NullPointerException
	at chanceCards.MoveCard.receiveCard(MoveCard.java:41)
	at fields.ChanceField.landOnField(ChanceField.java:25)
	at models.GameController.playerLandsOnField(GameController.java:81)
	at Main.playNormalTurn(Main.java:136)
	at Main.gameLoop(Main.java:85)
	at Main.gameLoop(Main.java:90)
	at Main.gameLoop(Main.java:90)
	at Main.gameLoop(Main.java:90)
	at Main.gameLoop(Main.java:90)
	at Main.gameLoop(Main.java:90)
	at Main.gameLoop(Main.java:90)
	at Main.gameLoop(Main.java:90)
	at Main.gameLoop(Main.java:90)
	at Main.gameLoop(Main.java:90)
	at Main.gameLoop(Main.java:90)
	at Main.gameLoop(Main.java:90)
	at Main.gameLoop(Main.java:90)
	at Main.gameLoop(Main.java:90)
	at Main.main(Main.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by algorythm** [comment]
Temporary fix.
Removing following line from the `ChanceCard` class:
`cCards.add(new MoveCard(13, Field.getFieldByID(16)));` (line 59)

**Comment by algorythm** [comment]
This probably replaces #67
